### ISSUE TITLE
Example 2 not compiling

### ISSUE THREAD

**Issue by RaduSoro** [nqminds/nqm-iot-database-utils#22]
On line 29 `arrayData = sqliteUtils.getNdarrayMeta(Buffer.from(array.buffer), "float64", [23, 34]);`

 throws compiling error **ReferenceError: arrayData is not defined**

it should be  `let arrayData = sqliteUtils.getNdarrayMeta(Buffer.from(array.buffer), "float64", [23, 34]);`

**Comment by mereacre** [comment]
Corrected
