### ISSUE TITLE
generalSchema is a fake singleton

### ISSUE THREAD

**Issue by aloisklink** [nqminds/nqm-iot-database-utils#32]
There is a singleton in `sqlite-manager.js`. Although Node.js is pretty good at caching `require` statements, so the singleton is really a singleton, I've managed to break that caching.

The singleton:

```js
const generalSchema = {};
```

To fix, either **a)** replace with a true-singleton, as in <https://derickbailey.com/2016/03/09/creating-a-true-singleton-in-node-js-with-es6-symbols/>, or **b)**, remove the need for a singleton.

**Comment by mereacre** [comment]
What is exactly the bug?

**Comment by aloisklink** [comment]
The test for the bug is in b7c480634572ff814ecf328e94dd87ac0ab6b6d4.

Essentially, when you `require("nqm-iot-database-utils")`, Node.js normally caches it, such that it's `generalSchema` object is shared with all processes. Unfortunately, I encountered a situation where `require("nqm-iot-database-utils")` isn't cached, and therefore there were two different `generalSchema`. This meant that code was in a broken state.
