### ISSUE TITLE
Race condition when constructing multiple Databases

### ISSUE THREAD

**Issue by aloisklink** [nqminds/nqm-iot-database-utils#41]
There's a race condition when creating the parent directory, when creating multiple databases at once. This should be an easy fix, since we can't just use `mkdirs`, or just wrap the folder creation code with a

```js
try {
  mkdirs();
} catch (error) {
  if (error.message !== "File Already Exists")
    throw error;
}

**Comment by IGlautier** [comment]
This only happens if you have two databases in the same target folder and try to create them at the same time.
