### ISSUE TITLE
Error in openDatabase

### ISSUE THREAD

**Issue by mereacre** [nqminds/nqm-iot-database-utils#43]
The function ```openDatabase``` returns:
```
{ [Error: EEXIST: file already exists, mkdir '.'] errno: -17, code: 'EEXIST', syscall: 'mkdir', path: '.' }
```
when invoked with the db path ```./test.sqlite```.

The error is here:
https://github.com/nqminds/nqm-iot-database-utils/blob/master/lib/sqlite-manager.js#L192

**Comment by aloisklink** [comment]
Hmm, that's weird. Are you using Node v10 or above? The `{"recursive": true}` option only works on Node v10 and above.

**Comment by mereacre** [comment]
Hmm, True. We need a warning when using the package that node needs to be of the right version or even a check.

**Comment by aloisklink** [comment]
I have set the `engines` field in `package.json` (see https://docs.npmjs.com/files/package.json#engines and https://github.com/nqminds/nqm-iot-database-utils/blob/master/package.json#L17), which _should_ raise a warning on install, but an Exception at runtime would be better.

**Comment by aloisklink** [comment]
This is a duplicate of #44
